//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/scripts/NAVEGACION/ControlHumano.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace ControlesHumanos
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/scripts/NAVEGACION/ControlHumano.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @ControlesHumanos: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @ControlesHumanos()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlHumano"",
    ""maps"": [
        {
            ""name"": ""MapaAndar"",
            ""id"": ""d7502ea8-50b0-408e-aaf1-3e43b791e7d5"",
            ""actions"": [
                {
                    ""name"": ""Moverse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""de69ccd2-8c33-4f96-bc98-eebeb39c7e49"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GirarVista"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a74d86d5-08db-4d43-a836-523d1d46c2b4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaltarLibre"",
                    ""type"": ""Button"",
                    ""id"": ""87c6a822-e469-43a2-8101-65efdcd3645d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Agacharse"",
                    ""type"": ""Button"",
                    ""id"": ""bdd2fcc9-804b-44c6-b697-7711d606ba25"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""6b6a71b0-ff56-4511-80fd-5635592cb8ec"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""daa51dfe-1263-418b-b980-a7649ab4065a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""477c973d-b542-418a-a3f7-717db191f9f7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b056c850-e9cd-401d-996e-ff06736351bc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ca5303a7-73e8-4b14-a791-094514b9f288"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""994acfd6-d9b8-4ba3-a7ec-3d27f31b3be0"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f65c9fda-f327-41b2-91dc-87f38f277e35"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GirarVista"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eae56a9b-c9a5-40ca-9811-a6e2b5083973"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GirarVista"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc59f84d-8bbb-49e3-ac69-b2f8c201282a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaltarLibre"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""241ebdca-923b-420a-8716-3f2002cc456f"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Agacharse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // MapaAndar
            m_MapaAndar = asset.FindActionMap("MapaAndar", throwIfNotFound: true);
            m_MapaAndar_Moverse = m_MapaAndar.FindAction("Moverse", throwIfNotFound: true);
            m_MapaAndar_GirarVista = m_MapaAndar.FindAction("GirarVista", throwIfNotFound: true);
            m_MapaAndar_SaltarLibre = m_MapaAndar.FindAction("SaltarLibre", throwIfNotFound: true);
            m_MapaAndar_Agacharse = m_MapaAndar.FindAction("Agacharse", throwIfNotFound: true);
        }

        ~@ControlesHumanos()
        {
            UnityEngine.Debug.Assert(!m_MapaAndar.enabled, "This will cause a leak and performance issues, ControlesHumanos.MapaAndar.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // MapaAndar
        private readonly InputActionMap m_MapaAndar;
        private List<IMapaAndarActions> m_MapaAndarActionsCallbackInterfaces = new List<IMapaAndarActions>();
        private readonly InputAction m_MapaAndar_Moverse;
        private readonly InputAction m_MapaAndar_GirarVista;
        private readonly InputAction m_MapaAndar_SaltarLibre;
        private readonly InputAction m_MapaAndar_Agacharse;
        /// <summary>
        /// Provides access to input actions defined in input action map "MapaAndar".
        /// </summary>
        public struct MapaAndarActions
        {
            private @ControlesHumanos m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public MapaAndarActions(@ControlesHumanos wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "MapaAndar/Moverse".
            /// </summary>
            public InputAction @Moverse => m_Wrapper.m_MapaAndar_Moverse;
            /// <summary>
            /// Provides access to the underlying input action "MapaAndar/GirarVista".
            /// </summary>
            public InputAction @GirarVista => m_Wrapper.m_MapaAndar_GirarVista;
            /// <summary>
            /// Provides access to the underlying input action "MapaAndar/SaltarLibre".
            /// </summary>
            public InputAction @SaltarLibre => m_Wrapper.m_MapaAndar_SaltarLibre;
            /// <summary>
            /// Provides access to the underlying input action "MapaAndar/Agacharse".
            /// </summary>
            public InputAction @Agacharse => m_Wrapper.m_MapaAndar_Agacharse;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_MapaAndar; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="MapaAndarActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(MapaAndarActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="MapaAndarActions" />
            public void AddCallbacks(IMapaAndarActions instance)
            {
                if (instance == null || m_Wrapper.m_MapaAndarActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MapaAndarActionsCallbackInterfaces.Add(instance);
                @Moverse.started += instance.OnMoverse;
                @Moverse.performed += instance.OnMoverse;
                @Moverse.canceled += instance.OnMoverse;
                @GirarVista.started += instance.OnGirarVista;
                @GirarVista.performed += instance.OnGirarVista;
                @GirarVista.canceled += instance.OnGirarVista;
                @SaltarLibre.started += instance.OnSaltarLibre;
                @SaltarLibre.performed += instance.OnSaltarLibre;
                @SaltarLibre.canceled += instance.OnSaltarLibre;
                @Agacharse.started += instance.OnAgacharse;
                @Agacharse.performed += instance.OnAgacharse;
                @Agacharse.canceled += instance.OnAgacharse;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="MapaAndarActions" />
            private void UnregisterCallbacks(IMapaAndarActions instance)
            {
                @Moverse.started -= instance.OnMoverse;
                @Moverse.performed -= instance.OnMoverse;
                @Moverse.canceled -= instance.OnMoverse;
                @GirarVista.started -= instance.OnGirarVista;
                @GirarVista.performed -= instance.OnGirarVista;
                @GirarVista.canceled -= instance.OnGirarVista;
                @SaltarLibre.started -= instance.OnSaltarLibre;
                @SaltarLibre.performed -= instance.OnSaltarLibre;
                @SaltarLibre.canceled -= instance.OnSaltarLibre;
                @Agacharse.started -= instance.OnAgacharse;
                @Agacharse.performed -= instance.OnAgacharse;
                @Agacharse.canceled -= instance.OnAgacharse;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MapaAndarActions.UnregisterCallbacks(IMapaAndarActions)" />.
            /// </summary>
            /// <seealso cref="MapaAndarActions.UnregisterCallbacks(IMapaAndarActions)" />
            public void RemoveCallbacks(IMapaAndarActions instance)
            {
                if (m_Wrapper.m_MapaAndarActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="MapaAndarActions.AddCallbacks(IMapaAndarActions)" />
            /// <seealso cref="MapaAndarActions.RemoveCallbacks(IMapaAndarActions)" />
            /// <seealso cref="MapaAndarActions.UnregisterCallbacks(IMapaAndarActions)" />
            public void SetCallbacks(IMapaAndarActions instance)
            {
                foreach (var item in m_Wrapper.m_MapaAndarActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MapaAndarActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="MapaAndarActions" /> instance referencing this action map.
        /// </summary>
        public MapaAndarActions @MapaAndar => new MapaAndarActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MapaAndar" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="MapaAndarActions.AddCallbacks(IMapaAndarActions)" />
        /// <seealso cref="MapaAndarActions.RemoveCallbacks(IMapaAndarActions)" />
        public interface IMapaAndarActions
        {
            /// <summary>
            /// Method invoked when associated input action "Moverse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMoverse(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "GirarVista" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGirarVista(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SaltarLibre" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSaltarLibre(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Agacharse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAgacharse(InputAction.CallbackContext context);
        }
    }
}
